[2024-10-26T07:54:36.677+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-26T07:54:36.775+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform_dim_payments manual__2024-10-26T07:54:35.648807+00:00 [queued]>
[2024-10-26T07:54:36.793+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform_dim_payments manual__2024-10-26T07:54:35.648807+00:00 [queued]>
[2024-10-26T07:54:36.794+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-26T07:54:36.845+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_dim_payments> on 2024-10-26 07:54:35.648807+00:00
[2024-10-26T07:54:36.854+0000] {standard_task_runner.py:63} INFO - Started process 1158 to run task
[2024-10-26T07:54:36.860+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'transform_dim_payments', 'manual__2024-10-26T07:54:35.648807+00:00', '--job-id', '708', '--raw', '--subdir', 'DAGS_FOLDER/e_commerce_dw_dag.py', '--cfg-path', '/tmp/tmp9g4nyups']
[2024-10-26T07:54:36.864+0000] {standard_task_runner.py:91} INFO - Job 708: Subtask transform_dim_payments
[2024-10-26T07:54:36.942+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.transform_dim_payments manual__2024-10-26T07:54:35.648807+00:00 [running]> on host eed3011aebc3
[2024-10-26T07:54:37.106+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='transform_dim_payments' AIRFLOW_CTX_EXECUTION_DATE='2024-10-26T07:54:35.648807+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-26T07:54:35.648807+00:00'
[2024-10-26T07:54:37.109+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-26T07:54:37.147+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-10-26T07:54:37.187+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-10-26T07:54:39.224+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-10-26T07:54:39.738+0000] {logging_mixin.py:188} INFO - Đã transform và lưu dữ liệu vào dim_payments
[2024-10-26T07:54:39.742+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-26T07:54:39.744+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-26T07:54:39.770+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=e_commerce_dw_etl, task_id=transform_dim_payments, run_id=manual__2024-10-26T07:54:35.648807+00:00, execution_date=20241026T075435, start_date=20241026T075436, end_date=20241026T075439
[2024-10-26T07:54:39.882+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-26T07:54:39.959+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T07:54:39.982+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
